name: Run tests

on:
  push:
    branches:
      - master
      - develop
      - "feature/*"
      - "hotfix/*"

  pull_request:
    branches:
      - master
      - develop
      - "feature/*"
      - "hotfix/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./package/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ./package

      - name: Run tests
        run: npm run test
        working-directory: ./package

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./package
